title: Callum Slowley # your name (or website title) here
logo: "/images/Temp.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Computer Games Technology Student at BCU 
  <br><br>
  Current University Project: 3D Games (boat game)
  <br><br>
  Current Personal Project: -----
  <br><br>
  <a href="https://www.linkedin.com/in/callum-slowley-87b288197">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://globalgamejam.org/users/paddog">View My Games Jam Profile</a> 
  <br><br>
  <a href="https://paddog.itch.io/">View My Itch.io Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
